FROM golang:1.17.0-windowsservercore-1809 AS build
WORKDIR /src/aws-secrets-manager
COPY ./go.mod ./go.sum ./
RUN go mod download
COPY . ./
RUN go build -o /app.exe -v ./cmd/aws-secrets-manager

FROM mcr.microsoft.com/windows/servercore:ltsc2019
COPY --from=build /app.exe /.
CMD ["/app.exe"]
